# Generated by Django 3.1.7 on 2023-06-24 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('deg_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('total_credits', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('UBa_Mentor_School', models.CharField(choices=[('Faculty of Economics and Management Sciences (FEMS)', 'FEMS'), ('College of Technology (COLTECH)', 'COLTECH'), ('Faculty of Education (FED)', 'FED'), ('Higher Institute of Transport and Logistics (HITL)', 'HITL')], default='Faculty of Economics and Management Sciences (FEMS)', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('teacher_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('course_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('credit', models.FloatField(null=True)),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], max_length=200, null=True)),
                ('subtype', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(choices=[('HND1', 'HND1'), ('HND2', 'HND2'), ('BTECH', 'BTECH')], max_length=200, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('level', models.CharField(choices=[('HND1', 'HND1'), ('HND2', 'HND2'), ('BTECH', 'BTECH')], max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pob', models.CharField(max_length=200, null=True)),
                ('degree_pursued', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.degree')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSession',
            fields=[
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], max_length=200)),
                ('ss_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('semester_start', models.DateField(default=datetime.datetime(2023, 6, 24, 13, 1, 24, 668473))),
                ('semester_end', models.DateField(default=datetime.datetime(2023, 6, 24, 13, 1, 24, 668473))),
                ('ca_deadline', models.DateField(default=datetime.datetime(2023, 6, 24, 13, 1, 24, 668473))),
                ('ca_deadline_btech', models.DateField(default=datetime.datetime(2023, 6, 24, 13, 1, 24, 668473))),
                ('result_deadline', models.DateField(default=datetime.datetime(2023, 6, 24, 13, 1, 24, 668473))),
                ('result_deadline_btech', models.DateField(default=datetime.datetime(2023, 6, 24, 13, 1, 24, 668473))),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('results_published', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('session', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='dept',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='HND1', max_length=10, null=True)),
                ('theory_marks', models.IntegerField(default=0, null=True)),
                ('term_test', models.IntegerField(default=0, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('dept', models.CharField(max_length=3, null=True)),
                ('resited', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('absent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('course_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('sem_ses', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.semestersession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'unique_together': {('student', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='RegisterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Approved', max_length=200)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('sem_ses', models.ForeignKey(default='S1/22/23', on_delete=django.db.models.deletion.CASCADE, to='app.semestersession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default='3')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('sem_ses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.semestersession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'unique_together': {('sem_ses', 'subject', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignedTeacher2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'course')},
            },
        ),
    ]
