# Generated by Django 3.1.7 on 2023-06-25 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='term_test_resit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='total_resit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 16, 11, 52, 671794)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 16, 11, 52, 671794)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 16, 11, 52, 671794)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 16, 11, 52, 671794)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 16, 11, 52, 671794)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 6, 25, 16, 11, 52, 671794)),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dept',
        ),
        migrations.AddField(
            model_name='subject',
            name='dept',
            field=models.ManyToManyField(to='app.Dept'),
        ),
    ]
