# Generated by Django 3.1.7 on 2023-07-18 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230625_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersession',
            name='ca_deadline_masters',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AddField(
            model_name='semestersession',
            name='result_deadline_masters',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 23, 29, 53, 419756)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept',
            field=models.ManyToManyField(blank=True, to='app.Dept'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('HND1', 'HND1'), ('HND2', 'HND2'), ('BTECH', 'BTECH'), ('M1', 'M1'), ('M2', 'M2')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subtype',
            field=models.CharField(choices=[('HND', 'HND'), ('DEGREE', 'DEGREE'), ('MASTER', 'MASTER')], default='HND', max_length=200, null=True),
        ),
    ]
