# Generated by Django 3.1.7 on 2023-08-14 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230718_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_masters',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_masters',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 23, 26, 27, 723753)),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('HND1', 'HND1'), ('HND2', 'HND2'), ('BTECH', 'BTECH'), ('M1', 'M1'), ('M2', 'M2')], max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registertable',
            unique_together={('student', 'subject', 'sem_ses')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'course_code', 'sem_ses')},
        ),
    ]
