# Generated by Django 3.1.7 on 2024-04-20 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240201_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_btech',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_masters',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_btech',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_masters',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 41000)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 12, 41, 49, 39994)),
        ),
    ]
