# Generated by Django 3.1.7 on 2023-04-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211212_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='session',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('L1', 'HND1'), ('L2', 'HND2')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('L1', 'HND1'), ('L2', 'HND2')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2')], max_length=200, null=True),
        ),
    ]
