# Generated by Django 3.1.7 on 2023-04-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230423_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('L1', 'HND1'), ('L2', 'HND2')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('L1', 'HND1'), ('L2', 'HND2')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('S1', 'Semester1'), ('S2', 'Semester 2')], max_length=200, null=True),
        ),
    ]
