# Generated by Django 3.1.7 on 2023-04-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20230424_0734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('student', 'subject')},
        ),
    ]
