# Generated by Django 3.1.7 on 2023-04-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20230428_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
