# Generated by Django 3.1.7 on 2023-04-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20230428_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='0000.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default='0000.jpeg', null=True, upload_to=''),
        ),
    ]
