# Generated by Django 3.1.7 on 2023-04-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20230428_0532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedteacher2',
            unique_together={('teacher', 'course_code')},
        ),
    ]
