# Generated by Django 3.1.7 on 2023-05-03 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20230503_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 5, 24, 43, 233768)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 5, 24, 43, 233768)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 5, 24, 43, 233768)),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('HND1', 'HND1'), ('HND2', 'HND2'), ('BTECH', 'BTECH')], max_length=200, null=True),
        ),
    ]
