# Generated by Django 3.1.7 on 2023-05-03 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20230503_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='dept',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 6, 17, 51, 600389)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 6, 17, 51, 600389)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 6, 17, 51, 600389)),
        ),
    ]
