# Generated by Django 3.1.7 on 2023-05-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20230503_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 11, 36, 11, 980769)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 11, 36, 11, 980769)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 11, 36, 11, 980769)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='session',
            field=models.CharField(default='2022/2023', max_length=9),
        ),
    ]
