# Generated by Django 3.1.7 on 2023-05-12 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20230512_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 12, 5, 13, 617674)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 12, 5, 13, 617674)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 12, 5, 13, 617674)),
        ),
    ]
