# Generated by Django 3.1.7 on 2023-05-12 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20230512_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedteacher2',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 45, 2, 158639)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 45, 2, 158639)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 45, 2, 158639)),
        ),
        migrations.AlterUniqueTogether(
            name='assignedteacher2',
            unique_together={('teacher', 'course')},
        ),
        migrations.RemoveField(
            model_name='assignedteacher2',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='assignedteacher2',
            name='student_dept',
        ),
    ]
