# Generated by Django 3.1.7 on 2023-05-13 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20230512_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='registertable',
            name='sem_ses',
            field=models.ForeignKey(default='S1/22/23', on_delete=django.db.models.deletion.CASCADE, to='main.semestersession'),
        ),
        migrations.AlterField(
            model_name='result',
            name='term_test',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='theory_marks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 19, 22, 24, 911892)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 19, 22, 24, 911892)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 19, 22, 24, 911892)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.academicyear'),
        ),
        migrations.CreateModel(
            name='ExamCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('sem_ses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semestersession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'unique_together': {('sem_ses', 'subject', 'student')},
            },
        ),
    ]
