# Generated by Django 3.1.7 on 2023-05-13 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20230513_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 20, 30, 27, 517383)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 20, 30, 27, 517383)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 20, 30, 27, 517383)),
        ),
    ]
