# Generated by Django 3.1.7 on 2023-05-14 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20230513_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='course_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 8, 52, 10, 328397)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 8, 52, 10, 328397)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 8, 52, 10, 328397)),
        ),
    ]
