# Generated by Django 3.1.7 on 2023-06-07 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20230607_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestersession',
            name='ca_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 17, 34, 11, 71294)),
        ),
        migrations.AddField(
            model_name='semestersession',
            name='result_deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 17, 34, 11, 71294)),
        ),
        migrations.AddField(
            model_name='semestersession',
            name='result_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 17, 34, 11, 71294)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 17, 34, 11, 71294)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 17, 34, 11, 71294)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 17, 34, 11, 71294)),
        ),
    ]
