# Generated by Django 3.1.7 on 2023-06-15 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20230608_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dept',
            name='UBa_Mentor_School',
            field=models.CharField(choices=[('Faculty of Economics and Management Sciences (FEMS)', 'FEMS'), ('College of Technology (COLTECH)', 'COLTECH'), ('Faculty of Education (FED)', 'FED'), ('Higher Institute of Transport and Logistics (HITL)', 'HITL')], default='Faculty of Economics and Management Sciences (FEMS)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 20, 11, 40, 253754)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='ca_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 20, 11, 40, 253754)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 20, 11, 40, 253754)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='result_deadline_btech',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 20, 11, 40, 253754)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_end',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 20, 11, 40, 253754)),
        ),
        migrations.AlterField(
            model_name='semestersession',
            name='semester_start',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 20, 11, 40, 253754)),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=''),
        ),
    ]
